### ISSUE TITLE
Soru

### ISSUE THREAD

**Issue by dulgermehmetakif** [dulgermuhammet/prvakdm#5]
index.php'yi çalıştırmam mı gerekiyor ?

**Comment by mad-cs** [comment]
Bu Windows bilgisayarlar için gösteriyor ama Debian'da da çalışır sanırım? Değil mi?

**Comment by mad-cs** [comment]
Galiba çalışır. Denerim.

**Comment by mad-cs** [comment]
#@dulgermuhammet Teşekkürler.
